# Generated by Django 4.2.6 on 2023-11-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Ingredient')),
                ('quantity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
            },
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Recipe')),
                ('photo', models.ImageField(default='default.png', upload_to='photo/', verbose_name='Photo')),
                ('cooking', models.TextField(verbose_name='Cooking method')),
                ('time_cook', models.TimeField(verbose_name='Cooking time')),
                ('slug', models.SlugField(unique=True)),
                ('ingredients', models.ManyToManyField(to='book.ingredients', verbose_name='Ingredients')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
            },
        ),
    ]
