# Generated by Django 4.2.6 on 2023-12-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_recipes_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='time_cook',
            field=models.CharField(max_length=10, verbose_name='Cooking time'),
        ),
    ]
