# Generated by Django 4.2.6 on 2023-12-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_recipes_time_cook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='type',
            field=models.CharField(choices=[('g', 'gm.'), ('p', 'pcs.')], default='g', max_length=20, verbose_name='Type'),
        ),
    ]
